/* Journey to Gate: local Prototype / Demo Data only. No network calls. */
const state={currentPage:'home',discovery:{query:'',filters:[]},selectedDestinations:[],itinerary:[],airport:{location:'gate-5',gate:'Gate 5',remainingMinutes:45},shopping:{selectedStores:[],category:'all',minutes:30,query:''}};
const dataService={getDestinations:()=>window.DESTINATIONS||[],getJdcStores:()=>window.JDC_STORES||[]};
let lastTrigger=null,selectedMapId=null;
function $(s){return document.querySelector(s)} function $$(s){return [...document.querySelectorAll(s)]}
function save(){try{localStorage.setItem('journeyToGate',JSON.stringify({selectedDestinations:state.selectedDestinations,itinerary:state.itinerary,shopping:state.shopping,currentPage:state.currentPage}))}catch(e){}}
function load(){try{const saved=JSON.parse(localStorage.getItem('journeyToGate'));if(saved)Object.assign(state,saved)}catch(e){}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function navigate(page){state.currentPage=page;$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));window.scrollTo(0,0);save();if(page==='discover')renderDiscover();if(page==='map')renderMap();if(page==='plan')renderPlan();if(page==='airport')renderAirport();if(page==='shopping')renderShopping();renderCounts();}
function renderCounts(){const n=state.itinerary.length;$('#planCount').textContent=n||'';$('#heroCount').textContent=`${n}개 장소`;}
function destMatches(d){const q=state.discovery.query.toLowerCase();if(q&&!`${d.name} ${d.area} ${d.category} ${d.description}`.toLowerCase().includes(q))return false;return state.discovery.filters.every(f=>f==='near'?d.airportDistanceLabel.includes('20분')||d.airportDistanceLabel.includes('30분')||d.airportDistanceLabel.includes('40분'):d[f]);}
function destinationCard(d){const inPlan=state.itinerary.includes(d.id);return `<article class="card"><span class="status">${d.accessibilityLabel} · DEMO</span><h2>${esc(d.name)}</h2><div class="meta">${esc(d.area)} / ${esc(d.category)} · ${esc(d.airportDistanceLabel)}</div><p>${esc(d.description)}</p><div class="badges"><span class="badge">${d.accessibleToilet?'휠체어 화장실':'화장실 정보 없음'}</span><span class="badge">${d.accessibleParking?'주차 고려':'주차 확인 필요'}</span><span class="badge neutral">${d.indoor?'실내':'야외'}</span></div><p class="meta">주의: ${esc(d.caution)}</p><div class="card-actions"><button data-trace="destinations" data-name="${esc(d.name)}">데이터 근거</button><button data-add-dest="${d.id}">${inPlan?'일정에서 제거':'일정에 추가'}</button></div></article>`}
function renderDiscover(){const arr=dataService.getDestinations().filter(destMatches);$('#destinationResults').innerHTML=arr.length?arr.map(destinationCard).join(''):`<div class="empty">조건에 맞는 장소가 없습니다. <button id="resetEmpty">조건 초기화</button></div>`;}
function renderMap(){const arr=dataService.getDestinations().filter(destMatches);$('#mapResults').innerHTML=arr.length?arr.map(d=>`<button class="map-result ${selectedMapId===d.id?'selected':''}" data-map-dest="${d.id}"><strong>${esc(d.name)}</strong><span class="meta">${esc(d.area)} · ${esc(d.accessibilityLabel)}</span></button>`).join(''):'<div class="empty">표시할 장소가 없습니다.</div>';const map=$('#jejuMap');map.querySelectorAll('.marker').forEach(x=>x.remove());arr.forEach(d=>{const b=document.createElement('button');b.className=`marker ${selectedMapId===d.id?'selected':''}`;b.style.left=`${d.mapPosition.x}%`;b.style.top=`${d.mapPosition.y}%`;b.title=d.name;b.setAttribute('aria-label',`${d.name} 선택`);b.dataset.mapDest=d.id;map.appendChild(b)});}
function addDestination(id){const d=dataService.getDestinations().find(x=>x.id===id);if(!d)return;const i=state.itinerary.indexOf(id);if(i>=0)state.itinerary.splice(i,1);else state.itinerary.push(id);save();renderDiscover();renderCounts();}
function renderPlan(){const items=state.itinerary.map(id=>dataService.getDestinations().find(d=>d.id===id)).filter(Boolean);let html=`<div class="timeline-item"><time>09:30</time><span class="dot"></span><div><strong>호텔 출발</strong><p>Demo itinerary start</p></div></div>`;if(!items.length)html+=`<div class="empty">아직 일정에 추가한 장소가 없습니다. 여행지를 찾아 하루를 만들어 보세요.</div>`;items.forEach((d,i)=>html+=`<div class="timeline-item"><time>${String(10+i*2).padStart(2,'0')}:10</time><span class="dot"></span><div><strong>${esc(d.name)}</strong><p>예시 이동 시간 약 ${20+i*5}분 · Demo travel estimate</p><button class="remove" data-remove-dest="${d.id}">일정에서 제거</button></div></div>`);if(items.length)html+=`<div class="timeline-item"><time>16:40</time><span class="dot"></span><div><strong>공항으로 이동</strong><p>Demo scenario · 공항 이동 권장 시간</p></div></div>`;$('#itinerary').innerHTML=html;}
function airportLayout(el){el.innerHTML='';['Gate 1','Gate 2','Gate 3','Gate 4','Gate 5','Gate 6','Gate 7'].forEach((g,i)=>{const x=document.createElement('span');x.className='gate';x.textContent=g;x.style.left=`${8+i*12}%`;x.style.top=`${i%2?58:48}%`;if(g==='Gate 5')x.style.background='#f3d38a';el.appendChild(x)});['JDC Zone A','JDC Zone B','JDC Zone C'].forEach((z,i)=>{const x=document.createElement('span');x.className='zone';x.textContent=z;x.style.left=`${22+i*23}%`;x.style.top='78%';el.appendChild(x)})}
function renderAirport(){airportLayout($('#airportMap'));}
function storeMatches(s){const q=state.shopping.query.toLowerCase();return state.shopping.category==='all'||s.category===state.shopping.category?(!q||`${s.brandName} ${s.products.join(' ')}`.toLowerCase().includes(q)):false;}
function storeCard(s){return `<article class="store-card"><h2>${esc(s.brandName)}</h2><span class="badge">${esc(s.category)}</span><p>${esc(s.products.join(' · '))}</p><p class="meta">${esc(s.locationLabel)} · Demo</p><button data-trace="jdcStores" data-name="${esc(s.brandName)}">Data Trace</button><button data-add-store="${s.id}">루트에 추가</button></article>`}
function buildShoppingRoute(){const candidates=dataService.getJdcStores().filter(storeMatches);const count=state.shopping.minutes<=10?1:state.shopping.minutes<=20?2:3;const picks=[...state.shopping.selectedStores.map(id=>dataService.getJdcStores().find(s=>s.id===id)).filter(Boolean),...candidates.filter(s=>!state.shopping.selectedStores.includes(s.id))].slice(0,count);$('#routeOutput').innerHTML=picks.length?`<h2>추천 쇼핑 루트 <small>· Prototype</small></h2><p>Gate 5에서 출발</p>${picks.map((s,i)=>`<div class="route-stop"><span>${i+1}. ${esc(s.brandName)}<br><small>${esc(s.category)}</small></span><b>예상 ${4+i*2}분</b></div>`).join('')}<div class="route-stop"><span>→ Gate 5</span><b>탑승 준비</b></div><p class="meta">Prototype route · 실제 공항 동선 API 연결 전 예시입니다.</p>`:`<div class="empty">선택한 조건에 맞는 매장이 없습니다. 조건을 변경해 보세요.</div>`;}
function renderShopping(){const arr=dataService.getJdcStores().filter(storeMatches);$('#storeResults').innerHTML=arr.length?arr.map(storeCard).join(''):`<div class="empty">조건에 맞는 매장이 없습니다. 조건을 변경해 보세요.</div>`;airportLayout($('#shoppingMap'));buildShoppingRoute();}
function openDataTrace(key,name,trigger){lastTrigger=trigger;const d=window.DATA_SOURCES[key];$('#modalTitle').textContent=`${name||d.dataset} · 데이터 근거`;$('#modalContent').innerHTML=`<p>${d.currentMode==='demo'?'현재 화면은 실제 운영 정보가 아닌 Prototype / Demo Data입니다.':''}</p><div class="trace-grid"><span>제공/설계</span><span>${esc(d.provider)}</span><span>사용 예정 데이터셋</span><span>${esc(d.dataset)}</span><span>현재 상태</span><span>Demo Local Dataset</span><span>향후 연결</span><span>${esc(d.futureMode)}</span></div>`;const m=$('#dataModal');m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');$('.modal-close').focus();}
function closeDataTrace(){const m=$('#dataModal');m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');if(lastTrigger)lastTrigger.focus();}
function init(){load();$$('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));$('#destinationSearch').addEventListener('input',e=>{state.discovery.query=e.target.value;renderDiscover()});$('#searchDest').addEventListener('click',renderDiscover);$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{const f=b.dataset.filter;state.discovery.filters=state.discovery.filters.includes(f)?state.discovery.filters.filter(x=>x!==f):[...state.discovery.filters,f];b.classList.toggle('active');renderDiscover()}));$('#clearDest').addEventListener('click',()=>{state.discovery={query:'',filters:[]};$('#destinationSearch').value='';$$('[data-filter]').forEach(x=>x.classList.remove('active'));renderDiscover()});$('#storeSearch').addEventListener('input',e=>{state.shopping.query=e.target.value;renderShopping()});$('#searchStore').addEventListener('click',renderShopping);$$('[data-minutes]').forEach(b=>b.addEventListener('click',()=>{state.shopping.minutes=+b.dataset.minutes;$$('[data-minutes]').forEach(x=>x.classList.toggle('selected',x===b));renderShopping()}));$$('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.shopping.category=b.dataset.category;$$('[data-category]').forEach(x=>x.classList.toggle('selected',x===b));renderShopping()}));document.addEventListener('click',e=>{const x=e.target.closest('[data-add-dest],[data-remove-dest],[data-map-dest],[data-add-store],[data-trace],#resetEmpty');if(!x)return;if(x.dataset.addDest)addDestination(x.dataset.addDest);if(x.dataset.removeDest){state.itinerary=state.itinerary.filter(i=>i!==x.dataset.removeDest);save();renderPlan();renderCounts()}if(x.dataset.mapDest){selectedMapId=x.dataset.mapDest;renderMap()}if(x.dataset.addStore){if(!state.shopping.selectedStores.includes(x.dataset.addStore))state.shopping.selectedStores.push(x.dataset.addStore);save();renderShopping()}if(x.dataset.trace)openDataTrace(x.dataset.trace,x.dataset.name,x);if(x.id==='resetEmpty')$('#clearDest').click()});$('.modal-close').addEventListener('click',closeDataTrace);$('#dataModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeDataTrace()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#dataModal').classList.contains('open'))closeDataTrace();if(e.key==='Tab'&&$('#dataModal').classList.contains('open')){const f=$$('#dataModal button,[href],[tabindex]:not([tabindex="-1"])');let i=f.indexOf(document.activeElement);if(e.shiftKey&&i===0){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&i===f.length-1){e.preventDefault();f[0].focus()}}});navigate(state.currentPage||'home');}
document.addEventListener('DOMContentLoaded',init);
