/* Local-only prototype: no network calls, no live airport or routing claims. */
const state={currentPage:'home',filters:[],query:'',selectedDestination:null,itinerary:[],gate:'Gate 5',shoppingMinutes:30,interests:['all'],selectedStores:[],storeQuery:''};
const dataService={getDestinations:()=>window.DESTINATIONS||[],getJdcStores:()=>window.JDC_STORES||[],getAirportInfo:()=>window.AIRPORT||{},getDataSources:()=>window.DATA_SOURCES||{}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let lastTrigger;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const tag=(v='DEMO DATA')=>`<span class="source-tag">${esc(v)}</span>`;
function save(){try{localStorage.setItem('journeyToGateV2',JSON.stringify(state))}catch(_){}}function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('journeyToGateV2'))||{})}catch(_){}}
function navigate(page){state.currentPage=page;$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});save();renderAll()}
function renderCounts(){let n=state.itinerary.length;$('#planCount').textContent=n||'';$('#heroCount').textContent=`${n}개 장소`}
function destMatches(d){let q=state.query.trim().toLowerCase(),hay=`${d.name} ${d.area} ${d.category} ${d.description}`.toLowerCase();return(!q||hay.includes(q))&&state.filters.every(f=>f==='near'?/20분|30분|40분/.test(d.airportDistanceLabel):d[f])}
function destinationCard(d){let planned=state.itinerary.includes(d.id),selected=state.selectedDestination===d.id;return `<article class="card ${selected?'selected-card':''}" data-destination-card="${d.id}"><div>${tag()} <span class="status">${esc(d.accessibilityLabel)}</span></div><h2>${esc(d.name)}</h2><div class="meta">${esc(d.area)} · ${esc(d.category)} · ${esc(d.airportDistanceLabel)}</div><p>${esc(d.description)}</p><div class="badges"><span class="badge">${d.accessibleToilet?'접근성 화장실':'화장실 정보 없음'}</span><span class="badge">${d.accessibleParking?'주차 고려':'주차 확인 필요'}</span><span class="badge neutral">${d.indoor?'실내':'야외'}</span></div><p class="meta">주의: ${esc(d.caution)}</p><div class="card-actions"><button data-trace="destinations" data-name="${esc(d.name)}">데이터 근거</button><button data-add-dest="${d.id}">${planned?'일정에서 제거':'일정에 추가'}</button></div></article>`}
function renderDiscover(){let a=dataService.getDestinations().filter(destMatches);$('#destinationResults').innerHTML=a.length?a.map(destinationCard).join(''):`<div class="empty">조건에 맞는 장소가 없습니다. <button id="resetEmpty">조건 초기화</button></div>`}
function selectDestination(id){state.selectedDestination=id;save();renderMap();renderDiscover()}
function renderMap(){let a=dataService.getDestinations().filter(destMatches),selected=dataService.getDestinations().find(d=>d.id===state.selectedDestination)||a[0];if(!state.selectedDestination&&selected)state.selectedDestination=selected.id;$('#mapResults').innerHTML=a.length?a.map(d=>`<button class="map-result ${d.id===state.selectedDestination?'selected':''}" data-map-dest="${d.id}" aria-pressed="${d.id===state.selectedDestination}"><strong>${esc(d.name)}</strong><span class="meta">${esc(d.area)} · ${esc(d.accessibilityLabel)}</span></button>`).join(''):`<div class="empty">표시할 장소가 없습니다.</div>`;let map=$('#jejuMap');map.querySelectorAll('.marker').forEach(x=>x.remove());a.forEach(d=>{let b=document.createElement('button');b.className=`marker ${d.id===state.selectedDestination?'selected':''}`;b.style.left=`${d.mapPosition.x}%`;b.style.top=`${d.mapPosition.y}%`;b.dataset.mapDest=d.id;b.setAttribute('aria-label',`${d.name} 선택`);map.append(b)});$('#mapDetail').innerHTML=selected?`<div><p class="eyebrow">SELECTED PLACE · ${tag()}</p><h2>${esc(selected.name)}</h2><p>${esc(selected.description)}</p><p class="meta">접근성: ${esc(selected.accessibilityLabel)} · 공항 이동: ${esc(selected.airportDistanceLabel)} · ${esc(selected.caution)}</p></div><button class="primary" data-add-dest="${selected.id}">${state.itinerary.includes(selected.id)?'일정에서 제거':'이 장소를 일정에 추가'}</button>`:''}
function addDestination(id){let i=state.itinerary.indexOf(id);i>=0?state.itinerary.splice(i,1):state.itinerary.push(id);state.selectedDestination=id;save();renderAll()}
function renderPlan(){let a=state.itinerary.map(id=>dataService.getDestinations().find(d=>d.id===id)).filter(Boolean),html=`<div class="timeline-item"><time>09:30</time><span class="dot"></span><div><strong>여행 출발</strong><p>Demo itinerary start</p></div></div>`;if(!a.length)html+=`<div class="empty">아직 일정에 추가한 장소가 없습니다. 여행지를 찾아 하루를 만들어 보세요.</div>`;a.forEach((d,i)=>html+=`<div class="timeline-item"><time>${String(10+i*2).padStart(2,'0')}:10</time><span class="dot"></span><div><strong>${esc(d.name)} ${tag()}</strong><p>접근성: ${esc(d.accessibilityLabel)} · 주의: ${esc(d.caution)}</p><p>이동 정보: 예시 ${20+i*5}분 · 실제 이동시간이 아닙니다.</p><button class="remove" data-move-dest="${d.id}" data-direction="up" ${i===0?'disabled':''}>위로</button><button class="remove" data-move-dest="${d.id}" data-direction="down" ${i===a.length-1?'disabled':''}>아래로</button><button class="remove" data-remove-dest="${d.id}">일정에서 제거</button></div></div>`);if(a.length)html+=`<div class="timeline-item transition"><time>16:40</time><span class="dot"></span><div><strong>공항 여정으로 전환</strong><p>예시 공항 이동 권장 시각 · Gate와 쇼핑 루트를 계속 설정할 수 있습니다.</p><button class="secondary" data-page="airport">공항 여정 시작</button></div></div>`;$('#itinerary').innerHTML=html}
function airportLayout(el){el.innerHTML='';['Gate 1','Gate 2','Gate 3','Gate 4','Gate 5','Gate 6','Gate 7'].forEach((g,i)=>{let n=document.createElement('button');n.className=`gate ${g===state.gate?'active-gate':''}`;n.textContent=g;n.style.left=`${8+i*12}%`;n.style.top=`${i%2?58:48}%`;n.dataset.gate=g;n.setAttribute('aria-label',`${g} 선택`);el.append(n)});['JDC Zone A','JDC Zone B','JDC Zone C'].forEach((z,i)=>{let n=document.createElement('span');n.className='zone';n.textContent=z;n.style.left=`${22+i*23}%`;n.style.top='78%';el.append(n)})}
function renderAirport(){$('#airportGate').textContent=state.gate;$('#airportShoppingMinutes').textContent=`${state.shoppingMinutes}분`;$('#gateControls').innerHTML=['Gate 1','Gate 2','Gate 3','Gate 4','Gate 5'].map(g=>`<button data-gate="${g}" class="${g===state.gate?'selected':''}" aria-pressed="${g===state.gate}">${g}</button>`).join('');airportLayout($('#airportMap'))}
function storeMatches(s){let q=state.storeQuery.toLowerCase();return(state.interests.includes('all')||state.interests.includes(s.category))&&(!q||`${s.brandName} ${s.products.join(' ')}`.toLowerCase().includes(q))}
function storeCard(s){let selected=state.selectedStores.includes(s.id);return `<article class="store-card ${selected?'selected-store':''}"><div>${tag('JDC DATA · DEMO')} <span class="badge">${esc(s.category)}</span></div><h2>${esc(s.brandName)}</h2><p>${esc(s.products.join(' · '))}</p><p class="meta">${esc(s.locationLabel)} · Prototype location</p><button data-trace="jdcStores" data-name="${esc(s.brandName)}">Data Trace</button><button data-add-store="${s.id}">${selected?'루트에서 제거':'루트에 추가'}</button></article>`}
function buildRoute(){let a=dataService.getJdcStores().filter(storeMatches),count=state.shoppingMinutes<=10?1:state.shoppingMinutes<=20?2:3,selected=state.selectedStores.map(id=>dataService.getJdcStores().find(s=>s.id===id)).filter(Boolean),stops=[...selected,...a.filter(s=>!state.selectedStores.includes(s.id))].slice(0,count);$('#routeOutput').innerHTML=stops.length?`<p class="eyebrow">RULE-BASED · PROTOTYPE ROUTE</p><h2>${state.shoppingMinutes}분 쇼핑 루트</h2><p>START · 현재 위치 (예시)</p>${stops.map((s,i)=>`<div class="route-stop"><span>${i+1}. ${esc(s.brandName)}<br><small>${esc(s.locationLabel)}</small></span><b>예상 ${4+i*3}분</b></div>`).join('')}<div class="route-stop"><span>RETURN · ${state.gate}</span><b>탑승 준비</b></div><p class="meta">Prototype Route입니다. 실제 최단 경로·실시간 이동 시간은 제공하지 않습니다.</p>`:`<div class="empty">조건에 맞는 매장이 없습니다.</div>`}
function renderShopping(){let a=dataService.getJdcStores().filter(storeMatches);$('#storeResults').innerHTML=a.length?a.map(storeCard).join(''):`<div class="empty">조건에 맞는 매장이 없습니다.</div>`;$$('#categoryControls button').forEach(b=>{b.classList.toggle('selected',state.interests.includes(b.dataset.category));b.setAttribute('aria-pressed',state.interests.includes(b.dataset.category))});$$('[data-minutes]').forEach(b=>{b.classList.toggle('selected',+b.dataset.minutes===state.shoppingMinutes);b.setAttribute('aria-pressed',+b.dataset.minutes===state.shoppingMinutes)});airportLayout($('#shoppingMap'));buildRoute()}
function openTrace(key,name,trigger){let d=dataService.getDataSources()[key];if(!d)return;lastTrigger=trigger;$('#modalTitle').textContent=`${name||d.dataset} · 데이터 근거`;$('#modalContent').innerHTML=`<p><strong>현재: DEMO DATA</strong> — 실제 운영 정보·실시간 정보가 아닌 로컬 프로토타입 데이터입니다.</p><h3>JDC DATA</h3><div class="trace-grid"><span>제공 / 연결</span><span>${esc(d.provider)}</span><span>사용 예정 데이터셋</span><span>${esc(d.dataset)}</span><span>Prototype mapping</span><span>Brand → brandName<br>Product → products<br>Location → locationLabel<br>Phone → phone</span><span>향후 연결</span><span>${esc(d.futureMode)}</span></div><h3>HOW IT BECOMES A SERVICE</h3><p>매장 정보 → 관심 품목과 매장 매칭 → 예시 쇼핑 루트 → Gate 복귀</p><p class="data-logic">DATA → DECISION → EXPERIENCE</p>`;let m=$('#dataModal');m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');$('.modal-close').focus()}
function closeTrace(){let m=$('#dataModal');m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');lastTrigger?.focus()}function renderAll(){renderCounts();renderDiscover();renderMap();renderPlan();renderAirport();renderShopping()}
function init(){load();$$('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));$('#destinationSearch').addEventListener('input',e=>{state.query=e.target.value;renderDiscover()});$('#searchDest').addEventListener('click',renderDiscover);$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{let k=b.dataset.filter;state.filters=state.filters.includes(k)?state.filters.filter(x=>x!==k):[...state.filters,k];b.classList.toggle('active');b.setAttribute('aria-pressed',state.filters.includes(k));renderDiscover()}));$('#clearDest').addEventListener('click',()=>{state.filters=[];state.query='';$('#destinationSearch').value='';$$('[data-filter]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});renderDiscover()});$('#storeSearch').addEventListener('input',e=>{state.storeQuery=e.target.value;renderShopping()});$('#searchStore').addEventListener('click',renderShopping);$$('[data-minutes]').forEach(b=>b.addEventListener('click',()=>{state.shoppingMinutes=+b.dataset.minutes;renderAll()}));$$('[data-category]').forEach(b=>b.addEventListener('click',()=>{let k=b.dataset.category;state.interests=k==='all'?['all']:[...state.interests.filter(x=>x!=='all'&&x!==k),k];if(!state.interests.length)state.interests=['all'];renderShopping()}));document.addEventListener('click',e=>{let x=e.target.closest('[data-add-dest],[data-remove-dest],[data-move-dest],[data-map-dest],[data-destination-card],[data-add-store],[data-trace],[data-gate],#resetEmpty');if(!x)return;if(x.dataset.addDest)addDestination(x.dataset.addDest);if(x.dataset.removeDest){state.itinerary=state.itinerary.filter(id=>id!==x.dataset.removeDest);renderAll()}if(x.dataset.moveDest){let i=state.itinerary.indexOf(x.dataset.moveDest),d=x.dataset.direction==='up'?-1:1;[state.itinerary[i],state.itinerary[i+d]]=[state.itinerary[i+d],state.itinerary[i]];renderPlan()}if(x.dataset.mapDest||x.dataset.destinationCard)selectDestination(x.dataset.mapDest||x.dataset.destinationCard);if(x.dataset.addStore){let id=x.dataset.addStore;state.selectedStores=state.selectedStores.includes(id)?state.selectedStores.filter(v=>v!==id):[...state.selectedStores,id];renderShopping()}if(x.dataset.gate){state.gate=x.dataset.gate;renderAll()}if(x.dataset.trace)openTrace(x.dataset.trace,x.dataset.name,x);if(x.id==='resetEmpty')$('#clearDest').click();save()});$('.modal-close').addEventListener('click',closeTrace);$('#dataModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeTrace()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#dataModal').classList.contains('open'))closeTrace();if(e.key==='Tab'&&$('#dataModal').classList.contains('open')){let f=$$('#dataModal button,[href],[tabindex]:not([tabindex="-1"])'),i=f.indexOf(document.activeElement);if(e.shiftKey&&i===0){e.preventDefault();f.at(-1).focus()}else if(!e.shiftKey&&i===f.length-1){e.preventDefault();f[0].focus()}}});navigate(state.currentPage||'home')}
document.addEventListener('DOMContentLoaded',init);
/* Buttons created while rendering the itinerary need delegated navigation. */
document.addEventListener('click',event=>{const button=event.target.closest('#itinerary [data-page]');if(button)navigate(button.dataset.page)});
